### ISSUE TITLE
请问您的联系邮箱是什么呀？想请教个问题

### ISSUE THREAD

**Issue by Heisenberg2015** [OleNet/IMVL-Framework#1]

**Comment by OleNet** [comment]
可以在这里描述吗？

**Comment by Heisenberg2015** [comment]
看到你修改了CNN-RelationExtraction，方便把测试数据或者整个程序发给我么。我这运行会出数据错误。（我是在校大学生，想学习下cnn）我邮箱：hbhb_2015@163.com   谢谢您了
